version: '3.8'

services:
  # Laravel Application
  app:
    container_name: direktory-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-local} # local by default
    ports:
      - "${APP_PORT:-8000}:80"
      - "5173:5173"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
      - vendor:/var/www/html/vendor
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - laravel

  # PostgreSQL Database
  db:
    container_name: direktory-db
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE:-direktory}
      - POSTGRES_USER=${DB_USERNAME:-username}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
  vendor: