version: '3.8'

services:
  # Laravel Application
  app:
    container_name: direktory-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"        # host port 8000 → container 80
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - laravel

  # PostgreSQL Database
  db:
    container_name: direktory-db
    image: postgres:15-alpine
    ports:
      - "5433:5432"       # host 5433 → container 5432
    environment:
      - POSTGRES_DB=direktory_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data: